In [1]:
%matplotlib inline
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense 
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
import pandas as pd
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [2]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = pd.read_csv('FinalFlight.csv')
data.shape
data.dtypes

Unnamed: 0                                int64
YEAR                                      int64
DAY_OF_MONTH                              int64
MONTH                                     int64
ORIGIN_AIRPORT_ID                         int64
OP_CARRIER_AIRLINE_ID                     int64
DISTANCE                                float64
inputLongitude                          float64
inputLatitude                           float64
DEP_TIME                                float64
SurfaceTemperatureFahrenheit            float64
SurfaceDewpointTemperatureFahrenheit    float64
RelativeHumidityPercent                   int64
SurfaceAirPressureMillibars               int64
CloudCoveragePercent                      int64
WindChillTemperatureFahrenheit          float64
WindSpeedMph                            float64
WindDirectionDegrees                      int64
PrecipitationPreviousHourInches         float64
SnowfallInches                          float64
cat_response                            

In [4]:
#split dataset in features and target variable
feature_cols = ['YEAR','DAY_OF_MONTH','MONTH','ORIGIN_AIRPORT_ID','OP_CARRIER_AIRLINE_ID','DISTANCE','inputLongitude','inputLatitude','DEP_TIME','SurfaceTemperatureFahrenheit','SurfaceDewpointTemperatureFahrenheit','RelativeHumidityPercent','SurfaceAirPressureMillibars','CloudCoveragePercent','WindChillTemperatureFahrenheit','WindSpeedMph','WindDirectionDegrees','PrecipitationPreviousHourInches','SnowfallInches']
X = data[feature_cols] # Features              
y = data.cat_response # Target variable
y

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        1
11        0
12        0
13        0
14        0
15        1
16        0
17        0
18        0
19        0
20        0
21        1
22        0
23        0
24        0
25        1
26        0
27        0
28        0
29        0
         ..
453278    1
453279    0
453280    1
453281    1
453282    0
453283    1
453284    0
453285    0
453286    0
453287    0
453288    0
453289    0
453290    1
453291    1
453292    0
453293    0
453294    0
453295    0
453296    0
453297    0
453298    1
453299    1
453300    0
453301    1
453302    0
453303    1
453304    1
453305    1
453306    0
453307    0
Name: cat_response, Length: 453308, dtype: int64

In [15]:


# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42) # 70% training and 30% test


In [16]:
model = Sequential([Dense(16, input_shape=(19,),activation='relu'), 
                    Dense(32, activation='relu'),Dense(2, activation='softmax')])

In [17]:
model.compile(Adam(lr=.0001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [18]:
model.fit(X_train,y_train, batch_size=20, epochs=20, shuffle= True, verbose=2)

Epoch 1/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 2/20
 - 31s - loss: 5.7146 - acc: 0.6455
Epoch 3/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 4/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 5/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 6/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 7/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 8/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 9/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 10/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 11/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 12/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 13/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 14/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 15/20
 - 26s - loss: 5.7146 - acc: 0.6455
Epoch 16/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 17/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 18/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 19/20
 - 25s - loss: 5.7146 - acc: 0.6455
Epoch 20/20
 - 25s - loss: 5.7146 - acc: 0.6455


In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 16)                320       
_________________________________________________________________
dense_5 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 66        
Total params: 930
Trainable params: 930
Non-trainable params: 0
_________________________________________________________________


In [20]:
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [21]:
eval_model=model.evaluate(X_train, y_train)
eval_model

362646/362646 [==============================] - 6s 16us/step


[5.714620119116213, 0.6454531416322188]

In [22]:
y_pred=model.predict(X_test)
#y_pred =(y_pred>0.5)
y_pred= np.argmax(y_pred, axis=1)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[58656,     0],
       [32006,     0]])

In [24]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: \n ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
    
cal_accuracy(y_test,y_pred)

Confusion Matrix: 
  [[58656     0]
 [32006     0]]
Accuracy :  64.69744766274734
Report :                precision    recall  f1-score   support

           0       0.65      1.00      0.79     58656
           1       0.00      0.00      0.00     32006

    accuracy                           0.65     90662
   macro avg       0.32      0.50      0.39     90662
weighted avg       0.42      0.65      0.51     90662

